[package]
name = "curscs/tut"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@1.7.0"
Component = "sleitnick/component@2.4.8"
Input = "sleitnick/input@2.3.0"
Trove = "sleitnick/trove@1.3.0"
TableUtil = "sleitnick/table-util@1.2.1"
Timer = "sleitnick/timer@1.1.2"